DELETE http://localhost:3001/api/persons/6082a94aa9d5e25f655267fa

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "James Bond",
  "number": "0123-456-007"
}